version: '3'

services:
  i2b2-web:
    image: i2b2-web:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - i2b2net
    depends_on:
      - i2b2-server
  i2b2-server:
    image: i2b2core-build:latest
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - i2b2net
    depends_on:
      - i2b2data-pg
  i2b2data-pg:
    image: i2b2data-pg:latest
    ports:
      - "5432:5432"
    networks:
      - i2b2net
    
networks: 
    i2b2net:
       driver: bridge